### PR TITLE
Bump .NET version and bump iOS packages.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
We might need the linker fixes for Android: https://github.com/xamarin/xamarin-android/pull/5610

**Comment by rolfbjarne** [comment]
@jonathanpeppers this happened, any idea why?

```
/usr/local/share/dotnet/sdk/6.0.100-preview.2.21114.3/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(109,5): error NETSDK1139: The target platform identifier android was not recognized.
/usr/local/share/dotnet/sdk/6.0.100-preview.2.21114.3/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(109,5): error NETSDK1139: The target platform identifier ios was not recognized.
```

**Comment by jonathanpeppers** [comment]
The Android `.pkg` creates `/usr/local/share/dotnet/sdk/6.0.100-preview.1.21103.13/EnableWorkloadResolver.sentinel` -- so it's the wrong version now.

We just got the linker fixes in but for 6.0.100-preview.1.21109.8, let me bump Android to the exact same build.

**Comment by jonathanpeppers** [comment]
We should have this one soon: https://github.com/xamarin/xamarin-android/pull/5669

I'll update the Android links here when we have them.

**Comment by jonathanpeppers** [comment]
Looks like the iOS build fails on Windows with:
```
Xamarin.Messaging.Build.targets(107,3): warning VSX1000: Not enough information has been provided to MSBuild in order to establish a connection to a Remote Server. The project 'HelloForms' will continue building offline [D:\a\1\s\HelloForms\HelloForms.csproj]
Xamarin.Messaging.Build.targets(107,3): warning VSX1000: The connection to the Mac Server with Address='' and User='' couldn't be established. The project 'HelloForms' will continue building offline [D:\a\1\s\HelloForms\HelloForms.csproj]
Xamarin.Messaging.Apple.targets(33,3): error MSB4018: The "VerifyXcodeVersion" task failed unexpectedly. [D:\a\1\s\HelloForms\HelloForms.csproj]
Xamarin.Messaging.Apple.targets(33,3): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'Xamarin.Localization.MSBuild, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. [D:\a\1\s\HelloForms\HelloForms.csproj]
Xamarin.Messaging.Apple.targets(33,3): error MSB4018: File name: 'Xamarin.Localization.MSBuild, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' [D:\a\1\s\HelloForms\HelloForms.csproj]
Xamarin.Messaging.Apple.targets(33,3): error MSB4018:    at Xamarin.iOS.Tasks.VerifyXcodeVersion.ExecuteAsync() [D:\a\1\s\HelloForms\HelloForms.csproj]
Xamarin.Messaging.Apple.targets(33,3): error MSB4018:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) [D:\a\1\s\HelloForms\HelloForms.csproj]
Xamarin.Messaging.Apple.targets(33,3): error MSB4018:    at Xamarin.iOS.Tasks.VerifyXcodeVersion.ExecuteAsync() [D:\a\1\s\HelloForms\HelloForms.csproj]
Xamarin.Messaging.Apple.targets(33,3): error MSB4018:    at Xamarin.iOS.Tasks.VerifyXcodeVersion.Execute() in /Users/builder/azdo/_work/1/s/xamarin-macios/msbuild/Xamarin.iOS.Tasks.Windows/Tasks/VerifyXcodeVersion.cs:line 14 [D:\a\1\s\HelloForms\HelloForms.csproj]
Xamarin.Messaging.Apple.targets(33,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [D:\a\1\s\HelloForms\HelloForms.csproj]
Xamarin.Messaging.Apple.targets(33,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [D:\a\1\s\HelloForms\HelloForms.csproj]
```
I get this locally, too. Is there a newer iOS package I could try?

**Pull request merged**
