### PR TITLE
Add scrollview to .NET MAUI sample & bot image

### PR DESCRIPTION
**Pull request by jamesmontemagno**
Screenshot_1615569156

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
Probably need to check this iOS & Catalyst, too. Do you have a screenshot of those?

**Comment by jamesmontemagno** [comment]
I don't :( I have it running only on Windows right now. The SVG should be just an SVG :) although i guess is ScrollView not implemented in the others?

**Comment by jonathanpeppers** [comment]
Yes, for example, `ScrollView` might be completly broken on Catalyst -- I'll try it.

**Comment by jamesmontemagno** [comment]
I have faith <3

**Review by jonathanpeppers — APPROVED** [review]
iOS (iPad):

image

Catalyst (seems to scroll, too):

image

**Comment by jamesmontemagno** [comment]
SHIP IT! <3 <3

**Pull request merged**
