### PR TITLE
Bump to .NET 6.0.100-preview.3.21201.23

### PR DESCRIPTION
**Pull request by jonathanpeppers**
* Android 11.0.200.195
* iOS 14.4.100.1320
* macOS 11.1.100.1373
* MacCatalyst 14.3.100.465
* Bump min iOS versions.

### CODE REVIEW

**Comment by rolfbjarne** [comment]
I think you'll need this too: https://github.com/dotnet/net6-mobile-samples/pull/110/commits/e52520dcf3779005cbf557e8688552f5cf13c46c

**Comment by jonathanpeppers** [comment]
@rolfbjarne this has a lot of warnings like:
```
ILLink : Trim analysis warning IL2045: System.Xml.Serialization.TypeScope.GetConstructorFlags(Type,Exception&): Attribute 'System.ObsoleteAttribute' is being referenced in code but the linker was instructed to remove all instances of this attribute. If the attribute instances are necessary make sure to either remove the linker attribute XML portion which removes the attribute instances, or override the removal by using the linker XML descriptor to keep the attribute type (which in turn keeps all of its instances). [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2070: System.Xml.Serialization.TypeScope.GetConstructorFlags(Type,Exception&): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors', 'DynamicallyAccessedMemberTypes.NonPublicConstructors' in call to 'System.Type.GetConstructor(BindingFlags,Type[])'. The parameter 'type' of method 'System.Xml.Serialization.TypeScope.GetConstructorFlags(Type,Exception&)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2070: System.Xml.Serialization.TypeScope.GetDefaultIndexer(Type,String): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors', 'DynamicallyAccessedMemberTypes.PublicMethods', 'DynamicallyAccessedMemberTypes.PublicFields', 'DynamicallyAccessedMemberTypes.PublicNestedTypes', 'DynamicallyAccessedMemberTypes.PublicProperties', 'DynamicallyAccessedMemberTypes.PublicEvents' in call to 'System.Type.GetDefaultMembers()'. The parameter 'type' of method 'System.Xml.Serialization.TypeScope.GetDefaultIndexer(Type,String)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2070: System.Xml.Serialization.TypeScope.GetDefaultIndexer(Type,String): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods' in call to 'System.Type.GetMethod(String,Type[])'. The parameter 'type' of method 'System.Xml.Serialization.TypeScope.GetDefaultIndexer(Type,String)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2070: System.Xml.Serialization.TypeScope.GetEnumeratorElementType(Type,TypeFlags&): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods' in call to 'System.Type.GetMethod(String,Type[])'. The parameter 'type' of method 'System.Xml.Serialization.TypeScope.GetEnumeratorElementType(Type,TypeFlags&)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2070: System.Xml.Serialization.TypeScope.GetEnumeratorElementType(Type,TypeFlags&): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods' in call to 'System.Type.GetMethod(String,Type[])'. The parameter 'type' of method 'System.Xml.Serialization.TypeScope.GetEnumeratorElementType(Type,TypeFlags&)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2075: System.Xml.Serialization.TypeScope.GetEnumeratorElementType(Type,TypeFlags&): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'System.Type.GetProperty(String)'. The return value of method 'System.Reflection.MethodInfo.ReturnType.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2070: System.Xml.Serialization.TypeScope.GetEnumeratorElementType(Type,TypeFlags&): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods', 'DynamicallyAccessedMemberTypes.NonPublicMethods' in call to 'System.Type.GetMethod(String,BindingFlags,Type[])'. The parameter 'type' of method 'System.Xml.Serialization.TypeScope.GetEnumeratorElementType(Type,TypeFlags&)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2070: System.Xml.Serialization.TypeScope.GetEnumeratorElementType(Type,TypeFlags&): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors', 'DynamicallyAccessedMemberTypes.NonPublicConstructors', 'DynamicallyAccessedMemberTypes.PublicMethods', 'DynamicallyAccessedMemberTypes.NonPublicMethods', 'DynamicallyAccessedMemberTypes.PublicFields', 'DynamicallyAccessedMemberTypes.NonPublicFields', 'DynamicallyAccessedMemberTypes.PublicNestedTypes', 'DynamicallyAccessedMemberTypes.NonPublicNestedTypes', 'DynamicallyAccessedMemberTypes.PublicProperties', 'DynamicallyAccessedMemberTypes.NonPublicProperties', 'DynamicallyAccessedMemberTypes.PublicEvents', 'DynamicallyAccessedMemberTypes.NonPublicEvents' in call to 'System.Type.GetMember(String,BindingFlags)'. The parameter 'type' of method 'System.Xml.Serialization.TypeScope.GetEnumeratorElementType(Type,TypeFlags&)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2070: System.Xml.Serialization.TypeScope.GetEnumeratorElementType(Type,TypeFlags&): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods' in call to 'System.Type.GetMethod(String,Type[])'. The parameter 'type' of method 'System.Xml.Serialization.TypeScope.GetEnumeratorElementType(Type,TypeFlags&)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2070: System.Xml.Serialization.TypeScope.ShouldBeReplaced(MemberInfo,Type,MemberInfo&): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties', 'DynamicallyAccessedMemberTypes.NonPublicProperties' in call to 'System.Reflection.TypeInfo.DeclaredProperties.get'. The parameter 'derivedType' of method 'System.Xml.Serialization.TypeScope.ShouldBeReplaced(MemberInfo,Type,MemberInfo&)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2070: System.Xml.Serialization.TypeScope.ShouldBeReplaced(MemberInfo,Type,MemberInfo&): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicFields', 'DynamicallyAccessedMemberTypes.NonPublicFields' in call to 'System.Reflection.TypeInfo.DeclaredFields.get'. The parameter 'derivedType' of method 'System.Xml.Serialization.TypeScope.ShouldBeReplaced(MemberInfo,Type,MemberInfo&)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2045: System.Xml.Serialization.XmlAttributes.XmlAttributes(ICustomAttributeProvider): Attribute 'System.ObsoleteAttribute' is being referenced in code but the linker was instructed to remove all instances of this attribute. If the attribute instances are necessary make sure to either remove the linker attribute XML portion which removes the attribute instances, or override the removal by using the linker XML descriptor to keep the attribute type (which in turn keeps all of its instances). [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2026: System.Xml.Serialization.XmlAttributes.IgnoreAttribute.get: Using method 'System.Reflection.Assembly.GetType(String)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Types might be removed. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2075: System.Xml.Serialization.XmlReflectionImporter.GetChoiceIdentifierType(XmlChoiceIdentifierAttribute,StructModel,Boolean,String): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'System.Type.GetProperty(String,BindingFlags)'. The return value of method 'System.Xml.Serialization.TypeModel.Type.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2075: System.Xml.Serialization.XmlReflectionImporter.GetChoiceIdentifierType(XmlChoiceIdentifierAttribute,StructModel,Boolean,String): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors', 'DynamicallyAccessedMemberTypes.PublicMethods', 'DynamicallyAccessedMemberTypes.PublicFields', 'DynamicallyAccessedMemberTypes.PublicNestedTypes', 'DynamicallyAccessedMemberTypes.PublicProperties', 'DynamicallyAccessedMemberTypes.PublicEvents' in call to 'System.Type.GetMember(String,BindingFlags)'. The return value of method 'System.Xml.Serialization.TypeModel.Type.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2070: System.Xml.Serialization.XmlReflectionImporter.GetMethodFromSchemaProvider(XmlSchemaProviderAttribute,Type): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods' in call to 'System.Type.GetMethod(String,BindingFlags,Type[])'. The parameter 'type' of method 'System.Xml.Serialization.XmlReflectionImporter.GetMethodFromSchemaProvider(XmlSchemaProviderAttribute,Type)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2075: System.Xml.Serialization.XmlSerializationILGen.GenerateBaseSerializer(String,String,String,CodeIdentifiers): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors', 'DynamicallyAccessedMemberTypes.NonPublicConstructors' in call to 'System.Type.GetConstructor(BindingFlags,Type[])'. The return value of method 'System.Collections.Generic.Dictionary<TKey,TValue>.Item.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2075: System.Xml.Serialization.XmlSerializationILGen.GenerateBaseSerializer(String,String,String,CodeIdentifiers): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors', 'DynamicallyAccessedMemberTypes.NonPublicConstructors' in call to 'System.Type.GetConstructor(BindingFlags,Type[])'. The return value of method 'System.Collections.Generic.Dictionary<TKey,TValue>.Item.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2075: System.Xml.Serialization.XmlSerializationILGen.GenerateGetSerializer(Dictionary<String,String>,XmlMapping[],TypeBuilder): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors', 'DynamicallyAccessedMemberTypes.NonPublicConstructors' in call to 'System.Type.GetConstructor(BindingFlags,Type[])'. The return value of method 'System.Collections.Generic.Dictionary<TKey,TValue>.Item.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2075: System.Xml.Serialization.XmlSerializationILGen.GenerateSerializerContract(String,XmlMapping[],Type[],String,String[],String,String[],Dictionary<String,String>): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors', 'DynamicallyAccessedMemberTypes.NonPublicConstructors' in call to 'System.Type.GetConstructor(BindingFlags,Type[])'. The return value of method 'System.Collections.Generic.Dictionary<TKey,TValue>.Item.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2075: System.Xml.Serialization.XmlSerializationILGen.GenerateSerializerContract(String,XmlMapping[],Type[],String,String[],String,String[],Dictionary<String,String>): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors', 'DynamicallyAccessedMemberTypes.NonPublicConstructors' in call to 'System.Type.GetConstructor(BindingFlags,Type[])'. The return value of method 'System.Collections.Generic.Dictionary<TKey,TValue>.Item.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2072: System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializer(String,String,XmlMapping,CodeIdentifiers,String,String,String): 'parent' argument does not satisfy 'All' in call to 'System.Xml.Serialization.CodeGenerator.CreateTypeBuilder(ModuleBuilder,String,TypeAttributes,Type,Type[])'. The return value of method 'System.Collections.Generic.Dictionary<TKey,TValue>.Item.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2075: System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializer(String,String,XmlMapping,CodeIdentifiers,String,String,String): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods', 'DynamicallyAccessedMemberTypes.NonPublicMethods' in call to 'System.Type.GetMethod(String,BindingFlags,Type[])'. The return value of method 'System.Collections.Generic.Dictionary<TKey,TValue>.Item.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2075: System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializer(String,String,XmlMapping,CodeIdentifiers,String,String,String): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods', 'DynamicallyAccessedMemberTypes.NonPublicMethods' in call to 'System.Type.GetMethod(String,BindingFlags,Type[])'. The return value of method 'System.Collections.Generic.Dictionary<TKey,TValue>.Item.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2075: System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializers(Dictionary<String,String>,TypeBuilder): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors', 'DynamicallyAccessedMemberTypes.NonPublicConstructors' in call to 'System.Type.GetConstructor(BindingFlags,Type[])'. The return value of method 'System.Collections.Generic.Dictionary<TKey,TValue>.Item.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2075: System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttributes(Member[],XmlSerializationReaderILGen.Member,String,LocalBuilder): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods', 'DynamicallyAccessedMemberTypes.NonPublicMethods' in call to 'System.Type.GetMethod(String,BindingFlags,Type[])'. The return value of method 'System.Xml.Serialization.TypeDesc.Type.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2075: System.Xml.Serialization.XmlSerializationReaderILGen.WriteAttributes(Member[],XmlSerializationReaderILGen.Member,String,LocalBuilder): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors', 'DynamicallyAccessedMemberTypes.NonPublicConstructors' in call to 'System.Type.GetConstructor(BindingFlags,Type[])'. The return value of method 'System.Xml.Serialization.TypeDesc.Type.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2075: System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceEnd(String,Type,Type): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods', 'DynamicallyAccessedMemberTypes.NonPublicMethods' in call to 'System.Type.GetMethod(String,BindingFlags,Type[])'. The return value of method 'System.Reflection.LocalVariableInfo.LocalType.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2075: System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceEnd(String,Type,Type): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors' in call to 'System.Type.GetConstructor(Type[])'. The return value of method 'System.Xml.Serialization.CodeGenerator.GetVariableType(Object)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2057: System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteCheckDefault(TypeMapping,String,Object,Boolean): Unrecognized value passed to the parameter 'typeName' of method 'System.Type.GetType(String)'. It's not possible to guarantee the availability of the target type. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2057: System.Xml.Serialization.XmlSerializationWriterCodeGen.WriteCheckDefault(TypeMapping,String,Object,Boolean): Unrecognized value passed to the parameter 'typeName' of method 'System.Type.GetType(String)'. It's not possible to guarantee the availability of the target type. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2075: System.Xml.Serialization.XmlSerializationWriterILGen.WriteArrayItems(ElementAccessor[],TextAccessor,ChoiceIdentifierAccessor,TypeDesc,String,String): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods' in call to 'System.Type.GetMethod(String,Type[])'. The return value of method 'System.Xml.Serialization.TypeDesc.Type.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2075: System.Xml.Serialization.XmlSerializationWriterILGen.WriteCheckDefault(SourceInfo,Object,Boolean): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods', 'DynamicallyAccessedMemberTypes.NonPublicMethods' in call to 'System.Type.GetMethod(String,BindingFlags,Type[])'. The return value of method 'System.Object.GetType()' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2075: System.Xml.Serialization.XmlSerializationWriterILGen.WriteElement(SourceInfo,ElementAccessor,String,Boolean): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods', 'DynamicallyAccessedMemberTypes.NonPublicMethods' in call to 'System.Type.GetMethod(String,BindingFlags,Type[])'. The return value of method 'System.Xml.Serialization.TypeDesc.Type.get' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [D:\a\1\s\HelloMaui\HelloMaui.csproj]
ILLink : Trim analysis warning IL2080: System.Xml.Serialization.XmlSerializationWriterILGen.WriteText(SourceInfo,TextAccessor): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicMethods', 'DynamicallyAccessedMemberTypes.NonPublicMethods' in call to 'System.Type.GetMethod(String,BindingFlags,Type[])'. The field 'System.Type System.Xml.Serialization.SourceInfo::Type' does not have matching annotations. The source value 
```
dotnet/maui has `WarningsAsErrors` turned on, so that is why my build was failing here: https://github.com/dotnet/maui/pull/592

**Comment by jonathanpeppers** [comment]
@rolfbjarne I think this will fix the warnings: https://github.com/xamarin/xamarin-macios/pull/10970

I did an equivalent in xamarin-android here: https://github.com/xamarin/xamarin-android/pull/5781

**Comment by jonathanpeppers** [comment]
The build fails here due to:
```
C:\Program Files\dotnet\packs\Microsoft.iOS.Windows.Sdk\14.4.100-ci.main.1271\tools\msbuild\iOS\Xamarin.Messaging.Build.targets(107,3): error MSB4018: The "SayHello" task failed unexpectedly.
System.Collections.Generic.KeyNotFoundException: The given key '16786' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(TKey key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Microsoft.Build.BackEnd.Logging.LoggingService.GetWarningsToBeLoggedAsErrorsByProject(BuildEventContext context)
   at Microsoft.Build.BackEnd.Logging.TaskLoggingContext.GetWarningsAsErrors()
   at Microsoft.Build.BackEnd.TaskHost.get_WarningsAsErrors()
   at Microsoft.Build.BackEnd.TaskHost.ShouldTreatWarningAsError(String warningCode)
   at Microsoft.Build.Utilities.TaskLoggingHelper.LogWarning(String subcategory, String warningCode, String helpKeyword, String helpLink, String file, Int32 lineNumber, Int32 columnNumber, Int32 endLineNumber, Int32 endColumnNumber, String message, Object[] messageArgs)
   at Microsoft.Build.Utilities.TaskLoggingHelper.LogWarningFromException(Exception exception)
   at Xamarin.Messaging.Build.Client.Tasks.SayHello.Execute() in C:\A\1\181\s\src\MSBuild\Xamarin.Messaging.Build.Client\Tasks\SayHello.cs:line 141
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [D:\a\1\s\fsharp\HelloiOSFSharp\HelloiOSFSharp.fsproj]
```

I think this must be an MSBuild bug.

**Comment by jonathanpeppers** [comment]
We need a dotnet/sdk with this fix: https://github.com/dotnet/msbuild/commit/17677364d656a98ce4c6eff73b49eddf24f0fd72

**Pull request merged**
